name: My Build
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/make-installer-windows.yml
    with:
      runner: "windows-latest"
      displayed_name: "Windows"
      msystem: "MINGW64"
      msys_package_env: "mingw-w64-x86_64"
      head_sha: ""
      artifact_version_suffix: ""
      extra_cmake_flags: ""
